#!/bin/bash
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.

tidybattery &
nm-applet --sm-disable &
start-pulseaudio-x11 -D
# udiskie --no-automount --auto-tray &

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

exec fluxbox # --screen 1
# or if you want to keep a log:
# exec fluxbox -log "~/.fluxbox/log"
